import type { DataProduct } from '../domain/data-exchange.ts'

export const dataExchangeCatalogVersion = 'data-exchange-catalog-v0.1.0'

export const dataProducts: DataProduct[] = [
  {
    category: 'crop-health',
    deliveryFormats: ['json', 'geojson', 'parquet'],
    description: 'Regional crop stress and disease-pressure index derived from weather, satellite metadata, and agronomic evidence fusion.',
    eligibleBuyers: ['government', 'insurance', 'cooperative', 'enterprise'],
    fields: [
      { description: 'Dissolved grid or administrative area identifier.', name: 'area_id', type: 'string' },
      { description: 'Crop family or crop group, never individual farmer identity.', name: 'crop_group', type: 'string' },
      { description: 'Fused disease-pressure posterior score from 0 to 1.', name: 'disease_pressure_score', type: 'number' },
      { description: 'Fused moisture-deficit posterior score from 0 to 1.', name: 'moisture_deficit_score', type: 'number' },
      { description: 'Model uncertainty from 0 to 1.', name: 'model_uncertainty', type: 'number' },
    ],
    governanceControls: ['k-anonymity threshold', 'field-boundary dissolution', 'source provenance manifest'],
    id: 'regional-crop-stress-index',
    license: 'Demeter Data Exchange License - aggregated analytics only',
    name: 'Regional Crop Stress Index',
    pricingUnit: 'EUR per 10k hectares per month',
    privacyClass: 'aggregated',
    sources: ['sentinel-2', 'weather', 'soilgrids'],
    spatialResolution: '1 km grid or administrative aggregate',
    temporalResolution: 'daily nowcast with historical snapshots',
    useCases: ['food-security monitoring', 'parametric insurance', 'cooperative advisory planning'],
  },
  {
    category: 'soil-water',
    deliveryFormats: ['json', 'parquet', 'stac-item'],
    description: 'Soil-water deficit and spray-window analytics for regional planning, irrigation prioritization, and input logistics.',
    eligibleBuyers: ['government', 'enterprise', 'cooperative', 'insurance'],
    fields: [
      { description: 'Aggregated area identifier.', name: 'area_id', type: 'string' },
      { description: 'Surface soil-moisture proxy.', name: 'soil_moisture_surface', type: 'number' },
      { description: 'Soil water-retention proxy from texture.', name: 'field_capacity_proxy', type: 'number' },
      { description: 'Wind and rainfall sprayability penalty.', name: 'sprayability_penalty', type: 'number' },
      { description: 'Source freshness classification.', name: 'freshness_class', type: 'string' },
    ],
    governanceControls: ['aggregation threshold', 'licensed downstream use', 'no raw farm boundary resale'],
    id: 'soil-water-deficit-grid',
    license: 'Demeter Data Exchange License - operational planning',
    name: 'Soil Water Deficit Grid',
    pricingUnit: 'EUR per region per season',
    privacyClass: 'aggregated',
    sources: ['weather', 'soilgrids'],
    spatialResolution: '1 km grid',
    temporalResolution: 'hourly weather refresh, daily aggregate',
    useCases: ['irrigation planning', 'spray logistics', 'input distribution planning'],
  },
  {
    category: 'supply-chain',
    deliveryFormats: ['json', 'parquet'],
    description: 'Crop condition and yield-risk signals for processors, commodity buyers, and supply-chain resilience teams.',
    eligibleBuyers: ['enterprise', 'cooperative', 'government'],
    fields: [
      { description: 'Crop region.', name: 'region', type: 'string' },
      { description: 'Crop group.', name: 'crop_group', type: 'string' },
      { description: 'Canopy vigor risk class.', name: 'canopy_vigor_class', type: 'string' },
      { description: 'Thermal stress posterior score.', name: 'thermal_stress_score', type: 'number' },
      { description: 'Recommended verification action.', name: 'verification_action', type: 'string' },
    ],
    governanceControls: ['regional aggregation', 'commercial-use license', 'decision provenance graph'],
    id: 'crop-supply-risk-feed',
    license: 'Demeter Enterprise Data License',
    name: 'Crop Supply Risk Feed',
    pricingUnit: 'EUR per crop-region feed per month',
    privacyClass: 'anonymized',
    sources: ['sentinel-2', 'weather', 'soilgrids', 'farmer-observation'],
    spatialResolution: 'crop-region aggregate',
    temporalResolution: 'weekly update with daily nowcast fields',
    useCases: ['procurement risk', 'supply-chain planning', 'regional agronomic monitoring'],
  },
  {
    category: 'food-security',
    deliveryFormats: ['json', 'geojson'],
    description: 'Government-facing early-warning indicators for climate exposure, crop stress, and agronomic intervention needs.',
    eligibleBuyers: ['government', 'research'],
    fields: [
      { description: 'Administrative unit code.', name: 'admin_area_code', type: 'string' },
      { description: 'Food-security alert level.', name: 'alert_level', type: 'string' },
      { description: 'Primary agronomic driver.', name: 'primary_driver', type: 'string' },
      { description: 'Evidence source count.', name: 'evidence_source_count', type: 'number' },
      { description: 'Human verification required.', name: 'requires_human_verification', type: 'boolean' },
    ],
    governanceControls: ['public-interest use restriction', 'privacy review', 'audit manifest'],
    id: 'public-sector-food-security-signals',
    license: 'Public Sector Analytics License',
    name: 'Public Sector Food Security Signals',
    pricingUnit: 'annual regional data agreement',
    privacyClass: 'aggregated',
    sources: ['sentinel-2', 'weather', 'soilgrids'],
    spatialResolution: 'administrative area',
    temporalResolution: 'daily nowcast and monthly archive',
    useCases: ['drought response', 'subsidy targeting', 'regional resilience planning'],
  },
]

export function getDataProduct(productId: string) {
  return dataProducts.find((product) => product.id === productId)
}
